Revert "mediapipe: add include and update visibility"
This reverts commit 47515dddcc8f09e62d1b169d1ae74de36a910009.

Reason for revert: It looks possible for Chromium to depend on
MediaPipe (https://source.chromium.org/chromium/chromium/src/+/main:third_party/mediapipe/features.gni;l=6-8;drc=6f557d86c8a3fe458b27ba90f3234d3fbab42983) hence this CL can cause ODR violations and macros clashes (CHECK is
alrady defined by Chromium).

Original change's description:
> mediapipe: add include and update visibility
>
> registration.h uses macros such as CHECK_*, so it needs to
> include absl's check. Without this errors such as the following are
> generated:
>
> In file included from ../../third_party/mediapipe/src/mediapipe/framework/api2/node.h:8:
> In file included from ../../third_party/mediapipe/src/mediapipe/framework/api2/contract.h:10:
> In file included from ../../third_party/mediapipe/src/mediapipe/framework/api2/packet.h:18:
> In file included from ../../third_party/mediapipe/src/mediapipe/framework/packet.h:30:
> ../../third_party/mediapipe/src/mediapipe/framework/deps/registration.h:274:7: error: use of undeclared identifier 'CHECK_EQ'
>   274 |       CHECK_EQ(1u, names.size())
>
> This also adds absl's log/check to a bunch of places that needed.
>
> Bug: None
> Change-Id: I7c0b19614ab4c1b3ab25c173390c8c2234b28bb1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4697420
> Reviewed-by: Rick Byers <rbyers@chromium.org>
> Commit-Queue: Scott Violet <sky@chromium.org>
> Reviewed-by: Robert Ogden <robertogden@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1171991}

Bug: None
Change-Id: I8e3cb1a9adccdfe69158e421ad242b848b71f785
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4701364
Auto-Submit: Mirko Bonadei <mbonadei@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Scott Violet <sky@chromium.org>
Commit-Queue: Mirko Bonadei <mbonadei@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1172327}
NOKEYCHECK=True
GitOrigin-RevId: 0ef86e7db3f138838c8aff03590cd3b1bbbdbc17